name: Make release

permissions:
  contents: write

on:
  workflow_dispatch: # allows manual triggering

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  create-tag:
    runs-on: ubuntu-22.04

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      name: ${{ steps.tag.outputs.name }}

    steps:
    - name: Clone
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        BUILD_NUMBER="$(git rev-list --count HEAD)"
        SHORT_HASH="$(git rev-parse --short=7 HEAD)"
        if [[ "${{ env.BRANCH_NAME }}" == "master-custom" ]]; then
          echo "name=b${BUILD_NUMBER}" >> $GITHUB_OUTPUT
        else
          SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
          echo "name=${SAFE_NAME}-b${BUILD_NUMBER}-${SHORT_HASH}" >> $GITHUB_OUTPUT
        fi

    - name: Create release
      id: create_release
      uses: anzz1/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: ${{ steps.tag.outputs.name }}

  build-all:
    needs:
    - create-tag

    strategy:
      matrix:
        include:
        - os: windows-latest
          os_suffix: windows-amd64
          reqs: cuda
          backend: cuda
          python-version: '3.12'
    runs-on: ${{ matrix.os }}
    env:
      BACKEND: ${{ matrix.backend }}
      BUILD_NAME: ${{ needs.create-tag.outputs.name }}
    steps:
    - name: Maximize build space
      if: matrix.os == 'ubuntu-20.04'
      uses: AdityaGarg8/remove-unwanted-software@v3
      with:
        remove-swapfile: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-android: 'true'
        remove-dotnet: 'true'
        # remove-large-packages: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/demo/package.json
    - name: Build voice changer client library
      shell: bash
      run: |
       cd client/lib
       npm install
       npm run build:prod
       cd -
    - name: Build client
      shell: bash
      run: |
        cd client/demo
        npm install
        npm install --save buffer @babel/runtime
        npm run build:prod
        cd -
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        # architecture: x64
        # cache: pip
    - name: Installing build dependencies
      run: python -m pip install --no-cache-dir --upgrade pip wheel setuptools pyinstaller
    - name: Install project deps + PyTorch CUDA
      shell: bash
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          --extra-index-url https://download.pytorch.org/whl/cu126 \
          -r requirements-common.txt -r requirements-${{ matrix.reqs }}.txt
    - name: Building executable
      run: pyinstaller --clean -y --dist ./dist --workpath /tmp MMVCServerSIO.spec
      working-directory: ./server
    - name: Copy utils
      run: cp ./server/{force_gpu_clocks.bat,reset_gpu_clocks.bat} ./server/dist/
      shell: bash
      if: matrix.os == 'windows-latest' && matrix.backend == 'cuda'
    - name: Copy starting config and bat
      run: cp ./server/{start.bat,.env} ./server/dist/MMVCServerSIO/
      shell: bash
      if: matrix.os == 'windows-latest' && matrix.backend == 'cuda'
    - name: Add CUDA library symlinks
      run: ln -svf nvidia/*/lib/*.so* .
      shell: bash
      if: matrix.os == 'ubuntu-20.04' && matrix.backend == 'cuda'
      working-directory: ./server/dist/MMVCServerSIO/_internal
    - name: Pack artifact
      shell: bash
      run: |
        mkdir ./server/artifacts
        if [ "$RUNNER_OS" = "Windows" ]; then
          7z a -v1500m -tzip ./server/artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.zip ./server/dist/* > /dev/null 2>&1
        else
          cd ./server/dist
          tar czf - ./* | split -b 1500m - ../artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.tar.gz.
          cd -
        fi
    - name: Rename single asset
      shell: bash
      run: |
        ls -al ./server/artifacts/
        COUNT=$(ls -1q ./server/artifacts/ | wc -l | sed -r 's/[[:space:]]+//g')
        if [ $COUNT = 1 ]; then
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv ./server/artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.zip.001 ./server/artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.zip
          else
            mv ./server/artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.tar.gz.aa ./server/artifacts/voice-changer-${{ matrix.os_suffix }}-${{ matrix.reqs }}.tar.gz
          fi
        fi
    - name: Upload assets with GH CLI
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME:      ${{ needs.create-tag.outputs.name }}
      run: |
        for f in ./server/artifacts/*; do
          echo "⏫ Uploading $f"
          gh release upload "$TAG_NAME" "$f" --repo "${{ github.repository }}" --clobber
        done
