name: Test Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build voice changer client library
        shell: bash
        run: |
          cd client/lib
          npm install
          npm run build:prod
          npm test
          cd -
      - name: Build client
        shell: bash
        run: |
          cd client/demo
          npm install
          npm install --save buffer @babel/runtime
          npm run build:prod
          cd -
